#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
	0xc2b648f9, 0x6ca082a6, 0x50d30dd7, 0xc7f70b11, 0x2d4c24d0, 0xc9f5719f, 0x50d3c292, 0x50d3135d, 0xbca50195, 0x50d3eafc,
	0x8c520eda, 0xc3c9e898, 0x2d4dfd76, 0x2d3f1b8b, 0xcf945eed, 0xac5ccda5, 0x2d4d105b, 0xc7f71436, 0x951c1e57, 0x2d4c6a99,
	0x6dbe9ef0, 0x2d4d0bca, 0xbca577c4, 0x51a9aedc, 0x951c4efd, 0x68ee96dc, 0xb2eee9e7, 0x2f4a91d6, 0xc2b642b7, 0xdfab2151,
	0xbca6ef36, 0x4818f2e0, 0xc2b64857, 0xd4ed24ac, 0x0e23c196, 0x8c523c1b, 0xadd160c3, 0x79a89a52, 0x50d3a416, 0x46b05387,
	0x55d6880c, 0x9242b37b, 0x518fc6ed,
};


static const unsigned int pnTestnetSeed[] = {

};
#endif
